
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_dalmacor?useSSL=false&serverTimezone=UTC
    password:
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    cors:
      allowed-origins: http://localhost:8080
  logging:
    level:
      root: INFO
      com.example: DEBUG